### ISSUE TITLE
Attempt to update object did not result in a single row modification

### ISSUE THREAD

**Issue by bilby91** [jeremyevans/sequel#1432] opened 2017-10-09 16:48 UTC
### Complete Description of Issue

We are seeing the following error multiple times and we are not sure of what is the source of the issue.

```
Attempt to update object did not result in a single row modification (SQL: UPDATE "api_keys" SET "last_accessed_at" = '2017-10-09 16:34:47.000000+0000' WHERE ("id" = 11061))
```

First thing that feels strange is how could it be possible to have more than one row for a query that is doing `id = X` ? Probably their is something that I'm not aware of that can be happening.

Another thing is that the problem shows up more easily when the concurrency of requests is higher. When we perform a load test with serial requests, the problem doesn't show up in general. When submitting multiple requests at the same time the error appears really quick.

### Simplest Possible Self-Contained Example Showing the Bug

The problem is showing when trying to update the column of a model.

```
@api_key = ApiKey.find(1)
@api_key.update(last_accessed_at: Time.zone.now)
```

### Full Backtrace of Exception (if any)

```
gems/sequel-4.49.0/lib/sequel/model/base.rb:2312 in _update
/gems/sequel-4.49.0/lib/sequel/model/base.rb:2305 in _update_columns
/gems/sequel-4.49.0/lib/sequel/model/base.rb:2252 in block (2 levels) in _save
/gems/sequel-4.49.0/lib/sequel/model/base.rb:1382 in around_update
/gems/sequel-4.49.0/lib/sequel/model/base.rb:2233 in block in _save
/gems/sequel-4.49.0/lib/sequel/model/base.rb:1382 in around_save
/gems/sequel-4.49.0/lib/sequel/model/base.rb:2207 in _save
/gems/sequel-4.49.0/lib/sequel/model/base.rb:1828 in block (2 levels) in save
/gems/sequel-4.49.0/lib/sequel/model/base.rb:2372 in block in checked_transaction
/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:224 in _transaction
/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:199 in block in transaction
/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301 in block in synchronize
/gems/sequel-4.49.0/lib/sequel/connection_pool/sharded_threaded.rb:133 in hold
/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301 in synchronize
/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:165 in transaction
/gems/sequel-4.49.0/lib/sequel/model/base.rb:2372 in checked_transaction
/gems/sequel-4.49.0/lib/sequel/model/base.rb:1828 in block in save
/gems/sequel-4.49.0/lib/sequel/model/base.rb:2360 in checked_save_failure
/gems/sequel-4.49.0/lib/sequel/model/base.rb:1828 in save
/gems/sequel-4.49.0/lib/sequel/model/base.rb:1841 in save_changes
/gems/sequel-4.49.0/lib/sequel/model/base.rb:2536 in update_restricted
/gems/sequel-4.49.0/lib/sequel/model/base.rb:1972 in update
```

**Comment by jeremyevans** [comment] 2017-10-09 17:00
Is there any chance the related rows are being deleted?  The error you get is for any time the number of updated rows is not 1, so it can occur if the number of rows is 0 (i.e. the related row has been deleted).  

If that is not it, you'll need to post a minimal, self-contained example showing the bug.  The example you posted is not self-contained, it's just a couple lines inside your current application.

Additionally, you may want to post what adapter you are using, just in case the adapter is not correctly reporting the number of rows.

Note that you can stop the check for unique rows by setting `ApiKey.require_modification = false`, but that just ignores the issue.

**Comment by bilby91** [comment] 2017-10-09 17:03
Jeremy,

Thanks for the quick reply!

I will investigate further an come back with a response for you comments. 

Martín

On Mon, Oct 09, 2017 at 14:00 Jeremy Evans

<
mailto:Jeremy Evans <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Is there any chance the related rows are being deleted? The error you get is for any time the number of updated rows is not 1, so it can occur if the number of rows is 0 (i.e. the related row has been deleted).

If that is not it, you'll need to post a minimal, self-contained example showing the bug. The example you posted is not self-contained, it's just a couple lines inside your current application.

Additionally, you may want to post what adapter you are using, just in case the adapter is not correctly reporting the number of rows.

Note that you can stop the check for unique rows by setting

ApiKey.require_modification = false

, but that just ignores the issue.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/jeremyevans/sequel/issues/1432#issuecomment-335218375
, or

**Comment by bilby91** [comment] 2017-10-09 18:59
@jeremyevans I can confirm that the problem is that this call https://github.com/jeremyevans/sequel/blob/master/lib/sequel/model/base.rb#L1793 is returning 0. 

I have verified that their is no db call to delete the record. We are using `sequel_pg (1.7.1)` as the adapter. 

I don't know if I will be able to reproduce this in a self-contained way. One other theory that maybe you can help me verify, could this be happening due to timeouts ? `_update` would return 0 if it timeout ?

Thanks for all the help before hand!

**Comment by jeremyevans** [comment] 2017-10-09 20:15
I don't think it could happen to a timeout.  A timeout when trying to execute a query should result in an exception being raised.

Another thing I think could cause this is if you are using preforking and not disconnecting before fork, or using the single connection pool when actually using multiple threads.  But both of those are likely to cause numerous other issues besides this one.

Is there any chance there is a trigger or rule on this table that would change the number of records returned, or that the backing dataset is a view and not a table?

Please try to develop a reproducible example for this issue, as otherwise I don't think I'll be able to help.  If it isn't possible to develop a reproducible example, it may be a local issue specific to your environment instead of a bug in Sequel.

**Comment by bilby91** [comment] 2017-10-09 20:30
@jeremyevans I will verify that their are no triggers that could be changing the records. The person responsible for managing the infrastructure is out for the week so I will ping you on Monday. I can confirm that the dataset is targeting a table and not a view.

One other thing that I noticed today is that previous select queries were starting to get slower and slower with the load tests. Increasing the max_connections and timeout helped a little bit to getter a better throughput but I think their is another issue here. Probably something from our environment and not a bug in `sequel` if I have to guess.

**Comment by jeremyevans** [comment] 2017-10-09 20:33
OK.  Since this is probably environment-specific, I'm going to close this now.  If you do think it is a bug in Sequel and not specific to your environment, please post a reproducible example and then I can test and possibly reopen.

**Closed by jeremyevans** 2017-10-09 20:33 UTC

**Comment by bilby91** [comment] 2017-10-09 20:35
@jeremyevans Will do. Thanks!

**Comment by bilby91** [comment] 2017-10-23 15:55
@jeremyevans The problem ended up being a concurrency issue. When concurrent request are trying to update the same row at the same time we having some deadlocks. Is it possible to lock a row using sequel (postgres db) ?

Thanks!

**Comment by jeremyevans** [comment] 2017-10-23 17:12
Yes.  You can use `Dataset#lock` to lock a whole table, `Dataset#for_update` to lock the rows of the dataset for update, or `Model#lock!` to lock the row for just the model instance.
