### ISSUE TITLE
connection stuck when DNS change due failover

### ISSUE THREAD

**Issue by fertobar** [jeremyevans/sequel#1491] opened 2018-04-06 23:16 UTC
### Complete Description of Issue
**pre condition**:  app in Ruby 2.2 with Puma connected ok via Sequel.
**failure scenario**: when there is an issue in DB we want to change the ELB, but in that moment  the app does not reconnect in automatic way until we force restart. 
in this case is scenario is stuck forever raising **Sequel::DatabaseConnectionError: PG::ConnectionBad** or *Sequel::PoolTimeout:* until I manual restart the instance 

Seems like endpoint is cached 

### Full Backtrace of Exception

sequel-5.2.0/lib/sequel/connection_pool/sharded_threaded.rb:243 in assign_connection
sequel-5.2.0/lib/sequel/connection_pool/sharded_threaded.rb:184 in acquire
sequel-5.2.0/lib/sequel/extensions/connection_validator.rb:98 in acquire
sequel-5.2.0/lib/sequel/connection_pool/sharded_threaded.rb:126 in hold
sequel-5.2.0/lib/sequel/database/connecting.rb:264 in synchronize
sequel-5.2.0/lib/sequel/adapters/postgres.rb:720 in literal_string_append

There is a way to force auto reconnection when DNS entry change?

**Comment by jeremyevans** [comment] 2018-04-06 23:27
Sequel doesn't do any caching of DNS entries, so if this is happening, it's happening at a lower level of the stack, such as in the database driver or operating system.  You should try replicating the issue using the database driver directly. As this doesn't appear to be a problem with Sequel itself, closing.

If you think this is problem with Sequel itself and not due to an issue in a lower level of the stack, please provide a minimal self contained example showing the problem along with a root cause analysis and I'll review.

**Closed by jeremyevans** 2018-04-06 23:27 UTC

**Comment by fertobar** [comment] 2018-04-06 23:30
ok, I will try to reproduce with small bunch of code to share

**Comment by fertobar** [comment] 2018-04-07 01:13
yes, I could confirm that after reduce the connection_validation_timeout from minutes to a few seconds recovery was almost immediate with failovers testing @jeremyevans .

**Comment by alexf101** [comment] 2019-11-07 23:19
@fertobar Looking for information here. I've got connection_expiration set to ~5 minutes to control the amount of idle connections, and connection_validation set to ~10 seconds to help with failover. However, it doesn't seem to be failing over until I restart the process. Should I take it from your statement that it's actually the maximum of the **connection_expiration_timeout** and the **connection_validation_timeout** that allows it to reconnect after a failover? I had assumed that the connection_validation_timeout would be enough, but it doesn't seem to be.
