### ISSUE TITLE
`DateAdd` silently fails to add when using unrecognised part type (including those which `ActiveSupport::Duration` allows)

### ISSUE THREAD

**Issue by bjeanes** [jeremyevans/sequel#1759] opened 2021-04-19 02:53 UTC
### Complete Description of Issue

I was having very strange behaviour in an app which I could not understand until I stepped through Sequel and saw the queries it was generating.

Essentially, Sequel supports accepting `ActiveSupport::Duration` but does not support all of its parts, such as `weeks`.

I would expect this to work or to error, preferably at instantiation of `DateAdd`.

### Simplest Possible Self-Contained Example Showing the Bug

Works with `{days: 1}` and `1.day`:

```
[38] pry(main)> db[:users].update(updated_at: Sequel.date_add(Sequel::CURRENT_TIMESTAMP, {days: 1}))
D, [2021-04-19T02:50:41.595851 #25] DEBUG -- :   Sequel (6.5ms)  UPDATE "users" SET "updated_at" = (CAST(CURRENT_TIMESTAMP AS timestamp) + CAST('1 days ' AS interval))

[39] pry(main)> db[:users].update(updated_at: Sequel.date_add(Sequel::CURRENT_TIMESTAMP, 1.day))
D, [2021-04-19T02:50:46.516912 #25] DEBUG -- :   Sequel (6.5ms)  UPDATE "users" SET "updated_at" = (CAST(CURRENT_TIMESTAMP AS timestamp) + CAST('1 days ' AS interval))
```

Silently drops the additive component with `{weeks: 1}` or `1.week`:

```
[40] pry(main)> db[:users].update(updated_at: Sequel.date_add(Sequel::CURRENT_TIMESTAMP, {weeks: 1}))
D, [2021-04-19T02:51:47.302581 #25] DEBUG -- :   Sequel (6.7ms)  UPDATE "users" SET "updated_at" = CAST(CURRENT_TIMESTAMP AS timestamp)

[41] pry(main)> db[:users].update(updated_at: Sequel.date_add(Sequel::CURRENT_TIMESTAMP, 1.week))
D, [2021-04-19T02:51:51.713059 #25] DEBUG -- :   Sequel (11.2ms)  UPDATE "users" SET "updated_at" = CAST(CURRENT_TIMESTAMP AS timestamp)
```

**Comment by jeremyevans** [comment] 2021-04-19 04:08
The `date_arithmetic` extension documentation currently shows examples using all supported keys.  I guess it could be more clear that those are the only keys supported.

I don't want to attempt to handle all possible keys.  I would prefer to keep things simple.

In terms of raising for unsupported keys, Sequel in general does not do that in terms of options to methods.  I suppose this case is slightly different, since these specify values and not options.  So I guess that change would be acceptable.  I can work on implementing that tomorrow.

**Comment by bjeanes** [comment] 2021-04-19 05:10
It seems reasonable to me not to try to support all keys, but some feedback when unsupported keys are encountered seems prudent.

That being said, does `ActiveSupport::Duration` doesn't appear to support any extra keys besides weeks, and given `date_arithmetic` accepts an AS `Duration`, I would advocate for supporting `weeks` in particular so that there is consistent behaviour when working with `Duration`s.

Is the issue here that not all DBs support weeks or just a general resistance to scope creep here?

**Comment by jeremyevans** [comment] 2021-04-19 15:37
Ah, I see.  If this issue was limited to the hash keys passed explicitly, I wouldn't think it was worth supporting, but the issue is this mishandles `ActiveSupport::Duration` instances that use weeks, and that is a bug that should be fixed.

Unfortunately, due to the way `date_sub` works, supporting this for `ActiveSupport::Duration` requires also supporting it for regular hashes.

Seems simplest to convert weeks to days automatically, because trying to support weeks for every database Sequel supports is probably a lot more work.  I'll work on that.

**Closed** 2021-04-19 15:54 UTC
