### ISSUE TITLE
jsonb breaks when using "hash-like" objects, for example `{}.with_indifferent_access`

### ISSUE THREAD

**Issue by AxlLind** [jeremyevans/sequel#1631] opened 2019-07-05 07:29 UTC
### Complete Description of Issue
If you have a sequel model with a jsonb column and use it with "hash-like" objects it now throws an error. For example with a sequel model `User` with a jsonb column `misc`:

```Ruby
props = {...}.with_indifferent_access
...
user.misc = props # throws error
```

Props is of type `ActiveSupport::HashWithIndifferentAccess` which is not found in the mappings in `pg_json.rb`, although it inherits from Hash.

Issue seems to be introduced in `5.21.0`.

### Full Backtrace of Exception (if any)
```
NoMethodError: undefined method `new' for nil:NilClass
from ~/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/sequel-5.22.0/lib/sequel/extensions/pg_json.rb:437:in `typecast_value_jsonb'
```

**Comment by janko** [comment] 2019-07-05 08:42
It's generally not a good idea to pass `ActiveSupport::HashWithIndifferentAccess` objects to other libraries, you'll eventually encounter some that don't support it. And libraries shouldn't have to support `ActiveSupport::HashWithIndifferentAccess`, that's a data structure of one particular library (ActiveSupport), you should only be using it inside the code that you own.

In this particular example, the reason Sequel doesn't handle it is because internally it maps the primitive object's class to its internal JSON class: https://github.com/jeremyevans/sequel/blob/83072aa3ba05110401a494f05f8cb75be215fb8f/lib/sequel/extensions/pg_json.rb#L175-L178

Since your object's class is `ActiveSupport::HashWithIndifferentAccess`, the JSON class is not found. But the error message could be improved by using `Hash#fetch` instead of `Hash#[]` in this line: https://github.com/jeremyevans/sequel/blob/83072aa3ba05110401a494f05f8cb75be215fb8f/lib/sequel/extensions/pg_json.rb#L437

I think it makes more sense that users convert their hash-like objects into a real Hashes before passing them to Sequel. In your case you can do it by calling `props.to_hash`.

**Comment by AxlLind** [comment] 2019-07-05 09:37
I can understand that passing random classes into libraries can be risky. Passing subclasses of Hash worked until `5.21.0` though. Now that's no longer supported which seems like a big undocumented change.

How do you feel about adding a `value = value.to_hash if value.is_a? Hash` or something similar in this case to make the sequel api easier to use?

**Comment by jeremyevans** [comment] 2019-07-05 14:15
Thanks for the report. This change wasn't intentional, and I think it is reasonable to expect that subclasses should continue to work.  I'll work on fixing it later today.  Since this is a regression from the previous release, it is subject to backporting in a 5.22.1 release.

**Comment by jeremyevans** [comment] 2019-07-05 15:34
Sorry, I read that wrong.  It didn't work in 5.21.0 and break in 5.22.0, it worked in 5.20 and broke in 5.21.0.  Since this isn't a regression in the latest release (5.22.0), it is not subject to backporting.  It will still be fixed in master later today.

**Closed** 2019-07-05 16:50 UTC
