### ISSUE TITLE
Error in reading integers from MySQL

### ISSUE THREAD

**Issue by hkarpf** [jeremyevans/sequel#1163] opened 2016-03-30 18:45 UTC
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue

```
(13.430000s) SELECT COLUMN1, COLUMN2, COLUMN3, COLUMN4 FROM TABLE WHERE COLUMN1 > '2016-03-20' AND COLUMN1< '2016-03-26' {:level=>:info, :file=>"WORKINGDIR/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/sequel-4.31.0/lib/sequel/database/logging.rb", :line=>"72", :method=>"log_each"}`
```
```
Exception when executing JDBC query {:exception=>#<Sequel::DatabaseError: Java::ComMysqlJdbcExceptionsJdbc4::MySQLDataException: '2.851733505E9' in column
'3' is outside valid range for the datatype INTEGER.>, :level=>:warn, :file=>"WORKINGDIR/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-i
nput-jdbc-3.0.0/lib/logstash/plugin_mixins/jdbc.rb", :line=>"201", :method=>"execute_statement"}←[0m
```

### Simplest Possible Self-Contained Example Showing the Bug
Trying to select data from a database (utilizing Sequel in the Logstash JDBC input plugin), and one column has IP's stored as integers...some are larger than 2147483648 (Max size for INT in MySQL).  I'm not sure it should be returning this error.  I can query the data just fine in something like MySQL Workbench.

**Comment by jeremyevans** [comment] 2016-03-30 20:34
This is an exception raised by the jdbc/mysql driver, so the problem seems to be there and not in Sequel itself.  You didn't submit a self contained example showing the bug, so I'm not sure how to reproduce this.  I'm going to close this now as this doesn't not appear to be an error in Sequel.  If you can come up with a self contained example showing the bug, please post it and I'll take another look.  You could try using jdbc/mysql directly and see if the results are different there.

**Closed by jeremyevans** 2016-03-30 20:34 UTC
