### ISSUE TITLE
Add :stream => false option

### ISSUE THREAD

**Issue by Aryk** [jeremyevans/sequel#1394] opened 2017-07-04 13:06 UTC
Discussed [here](https://groups.google.com/forum/#!topic/sequel-talk/lqYvmex9ojo).

I'm going to submit a PR to address this.

**Comment by jeremyevans** [comment] 2017-07-04 15:48
Closing, tracking on #1395.  Note that an issue shouldn't be opened for this, as it is not a bug, but a request for a new feature.

**Closed by jeremyevans** 2017-07-04 15:48 UTC

**Comment by Aryk** [comment] 2017-07-05 06:35
ok, i won't open issues for feature add-ons.
