### ISSUE TITLE
after_commit does not respect rollbacks

### ISSUE THREAD

**Issue by rgalanakis** [jeremyevans/sequel#1587] opened 2019-01-07 05:20 UTC
### Complete Description of Issue

I am using the `after_commit` hook to hook into another system after a transaction commits.

If I have an inner transaction with a savepoint, which adds an after_commit hook, and that transaction rolls back, the after_commit hook (set up while in the savepoint-ed transaction) is run.

The documentation states:

> If a transaction is not currently in process, yield to the block immediately. Otherwise, add the block to the list of blocks to call after the currently in progress transaction commits (and only if it commits).

This seems to me like it should support savepoints, so I was taken by surprise if this is expected behavior. I would also find it surprising that commit hooks added in rolled back transactions would run, since we know their behavior would not be observable (since they were rolled back).

### Simplest Possible Self-Contained Example Showing the Bug

Setup is something like `model = Milkrun::User.first`, just any model. Using Postgres 11.1, not tested on other versions. Using Sequel 5.16. I tried with the `rollback_on_exit` feature but it did not work.

I would expect this to print `["outer"]`:

```ruby
ran_hooks = []
model.db.transaction do
  model.db.after_commit do
    ran_hooks << 'outer'
  end
  model.db.transaction(savepoint: true) do
    model.db.after_commit do
      ran_hooks << 'inner'
    end
    raise Sequel::Rollback
  end
end
pp ran_hooks
# ['outer', 'inner']
```

This is empty, as expected:
```ruby
ran_hooks = []
model.db.transaction(savepoint: true) do
  model.db.after_commit do
    ran_hooks << 'inner'
  end
  raise Sequel::Rollback
end
pp ran_hooks
# []
```

To double check that it wasn't something like "inner transactions do not change the definition of 'current' unless they are in savepoints", I did some nested savepoints with a rollback. I would expect `["outer", "middle"]`:

```ruby
ran_hooks = []
model.db.transaction(savepoint: true) do
  model.db.after_commit do
    ran_hooks << 'outer'
  end
  model.db.transaction(savepoint: true) do
    model.db.after_commit do
      ran_hooks << 'middle'
    end
    model.db.transaction(savepoint: true) do
      model.db.after_commit do
        ran_hooks << 'inner'
      end
      raise Sequel::Rollback
    end
  end
end
pp ran_hooks
# ["outer", "middle", "inner"]
```

And for good measure, the SQL log of the last example:

```
[2019-01-06 21:08:25.324695 36560/main] debug {} -- (0.000277s) BEGIN
[2019-01-06 21:08:25.325011 36560/main] debug {} -- (0.000155s) SAVEPOINT autopoint_1
[2019-01-06 21:08:25.325182 36560/main] debug {} -- (0.000078s) SAVEPOINT autopoint_2
[2019-01-06 21:08:25.325443 36560/main] debug {} -- (0.000133s) ROLLBACK TO SAVEPOINT autopoint_2
[2019-01-06 21:08:25.325601 36560/main] debug {} -- (0.000081s) RELEASE SAVEPOINT autopoint_1
[2019-01-06 21:08:25.325772 36560/main] debug {} -- (0.000116s) COMMIT
```

One more note- I tried `db.rollback_on_exit(savepoint: true)` instead of `raise Sequel::Rollback` but got the same result. Using `db.rollback_on_exit` (no arguments) did not run the hooks, but that is because nothing was committed (I assume).

**Comment by jeremyevans** [comment] 2019-01-07 05:49
Thanks for the detailed description of the problem.  However, this is expected behavior.  `after_commit` is transaction-level, not savepoint level.  Technically, savepoints are not committed, they are released.

The reason the empty example works as you expect is that does not create a savepoint, only a transaction.

Sequel doesn't currently offer an API for "run block when transaction commits, if all enclosing savepoints are released and not rolled back".  I'm not sure such an API is widely enough needed to deserve adding support to core.  You could ask on the sequel-talk Google Group and see to what extent other Sequel users have a need for it.

If you think the documentation should be updated to explicitly mention that `after_commit` does not support savepoints, please send a documentation pull request.

**Closed by jeremyevans** 2019-01-07 05:49 UTC

**Comment by rgalanakis** [comment] 2019-01-07 06:18
Understood- thanks! I'll try to update the docs this week.
