### ISSUE TITLE
after_create don't act as expected

### ISSUE THREAD

**Issue by youjiuzidangge** [jeremyevans/sequel#1560] opened 2018-10-18 11:17 UTC
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue
i have two project A,B which share the same db.

and in project A, there is a model(let's call Student) which has a after create hook. In the hook, there is a request to project B api, and first thing that B api does is to get the student created in project A just now. but there is no student.

### Simplest Possible Self-Contained Example Showing the Bug
Project A:
  class Student
     def after_create
       super
       http_put_request(uri, id)
     end
  end

Project B:
   code in http_put_request
       Student.find(student_id_from_project_A)

RecordNotFound

**Comment by jeremyevans** [comment] 2018-10-18 13:34
This is not a bug, it's due to the fact that model saving uses transactions by default. You probably want:

```ruby
def after_create
  super
  db.after_commit{http_put_request(uri, id)}
end
```

Otherwise the `http_put_request` method is called before the transaction is committed.

**Closed by jeremyevans** 2018-10-18 13:34 UTC
