### ISSUE TITLE
Sequel.blob encoding issues in Postgres

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [jeremyevans/sequel#983] opened 2015-04-03 20:40 UTC
Apologies if this is a `pg` instead of a `sequel` one--I think the problem might be in `Sequel.blob`, but I'm not familiar with the code and looking through it a bit, I'm still not sure.

We're using `pg` 0.17.1 and `sequel` 4.17.0.

So:

We have a workload where we encrypt some values using my gem `attr_vault` (the Sequel-relevant part is mostly in the `before_save` hook [here](https://github.com/uhoh-itsmaciek/attr_vault/blob/master/lib/attr_vault.rb#L14)). This particular workload always updates the encrypted attribute to either `nil` or an 80-byte `Sequel.blob`. This works great most of the time, but we occasionally run into situations where the length of the values in the corresponding `bytea` column in Postgres (via the `octet_length` function) is significantly more than 80 (and sure enough, we can't read out the encrypted data--it's been corrupted somehow)

Furthermore, the distribution of bytes in the values that are 80 bytes long is pretty even: each byte occurs with about the same frequency. For the corrupted values (the ones more than 80 bytes long), the bytes corresponding to the UTF8 (our database encoding) characters '\', '0', '1', '2', '3', '4', '5', '6', and '7' occur 30x (or more) more frequently than any of the other bytes. This is suspiciously similar to characters one might expect to see frequently in the old ['escape' `bytea` format](http://www.postgresql.org/docs/9.3/static/datatype-binary.html#AEN5383).

I don't believe we're concurrently modifying the model instances (or using Sequel in other concurrency-unsafe ways), but this is in a large codebase and I have not been able to reproduce it standalone.

Could this be a Sequel issue with encoding blobs?

**Comment by jeremyevans** [comment] 2015-04-03 21:13
As far as I'm aware, there is no general issue with how Sequel encodes blobs on PostgreSQL.  4.17.0 had a fix for using `Sequel::SQL::Blob` values in prepared statements/bound variables, but you said you are already using that.

Any chance you could come up with a self contained example showing the problem?  What version of PostgreSQL are you using?

For earlier detection of this probably, add a CHECK constraint for an octet_length of 80 for the column.  That way if something tries to insert/update something with a non-80 octet_length, it will raise an error.

**Comment by uhoh-itsmaciek** [comment] 2015-04-03 21:32
Ok, thanks. We're on 9.1.12--a few point releases behind but I don't see anything in the release notes that could manifest like this. We have a PR in review for the check constraint already--great suggestion.

I'll try again to make a self-contained reproduction--I haven't had much luck so far but it occurs to me I was running against a different database version.

**Comment by jeremyevans** [comment] 2015-04-03 21:40
OK.  I'm going to close this now.  If you can come up with a reproducible example, I'll review it and reopen.

Any chance the invalid data was added before you upgraded to Sequel 4.17.0?

**Closed by jeremyevans** 2015-04-03 21:40 UTC

**Comment by uhoh-itsmaciek** [comment] 2015-04-03 22:23
Actually, looking at our Gemfile history, we upgraded to 4.17.0 around December 22nd and have had zero instances of the problem in data created *after* that, so maybe this bug is actually a distant cousin (or dupe) of #917. I suppose if backslashes were being escaped as well as single quotes, I could see that inadvertently shifting things between the two different input formats.

Anyway, I think that might have been it. I think we can manually clean up the existing corrupted data. Thanks for your help.

**Comment by uhoh-itsmaciek** [comment] 2015-04-04 02:47
Actually, it looks like while the above is true for *one* of the tables where we store this data, another table using the same mechanism is still receiving bogus writes as recently as today (so with Sequel 4.17.0). Interestingly, the first table has two `bytea` (encrypted) fields, and *most* of the corruption happens in both fields at once. This seems really weird, since the two fields are entirely unrelated (and for what it's worth, we used to store both fields as `text` and never had any problems).

As per my earlier comment, I'll try to repro, but I concede that there's not much info from me to track down a potential issue in Sequel here right now.

**Comment by jeremyevans** [comment] 2015-04-04 02:59
OK, if you find out anything, please post back here.  Hopefully with the CHECK constraint added it will be easier to track down the root cause of the problem.

**Comment by uhoh-itsmaciek** [comment] 2015-04-10 21:57
We've added CHECK constraints and they do seem to be preventing the bogus data, but I haven't tracked down the root cause yet. It occurs to me that this could be because we connect to a *lot* of different databases, 9.1 through 9.4, with different values for `bytea_output` and potentially other relevant settings. We only use models in our main database (9.1); we pass a block to `Sequel.connect` to talk to the others. Does Sequel store any module-level state that could cause problems for usage patterns like this?

**Comment by jeremyevans** [comment] 2015-04-12 06:16
No, Sequel does not store any module level state as far as I know that would effect how code runs.  The only module level state sets the defaults for new Database instances.  In terms of bytea support, Sequel always calls the `PGconn#escape_bytea` method to literalize `Sequel.blob` values (and `Sequel.blob` bound variables are sent verbatim in binary mode).  Do you have a backtrace from one of the CHECK constraint failures?

**Comment by uhoh-itsmaciek** [comment] 2015-04-12 20:19
Great question. I haven't had a chance to investigate yet, but the backtrace follows below The 'shogun' parts are proprietary code that I can't share but hopefully that's not relevant here. I included the full trace to avoid screwing things up while redacting, since there's nothing especially secret in the file and method names anyway.

The general idea in this process is that this is a Sidekiq worker that ticks "resources" based on a state machine (like [aasm](https://github.com/pluginaweek/state_machine) or [state_machine](https://github.com/pluginaweek/state_machine), but home-grown). In this case, in the course of ticking the state, we need to look up some metadata cached locally but it's not available, so we call out to another API to fetch it (the `ensure_heroku_resource` call). It's this metadata that is encrypted and runs the `before_save` hook I mentioned above.

If nothing obvious jumps out from the backtrace, I'll try to get more info regarding the discrepancy between what ends up in Postgres and the bytea values we tried to put in there (at the time the check constraint violation occurs, I *should* have both available I think).

```
#<Sequel::CheckConstraintViolation: PG::CheckViolation: ERROR: new row for relation "heroku_resources" violates check constraint "valid_log_input_url"
>
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/adapters/postgres.rb:168:in `async_exec'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/adapters/postgres.rb:168:in `block in execute_query'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/database/logging.rb:33:in `log_yield'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/adapters/postgres.rb:168:in `execute_query'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/adapters/postgres.rb:155:in `block in execute'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/adapters/postgres.rb:131:in `check_disconnect_errors'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/adapters/postgres.rb:155:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/adapters/postgres.rb:499:in `_execute'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/adapters/postgres.rb:323:in `block (2 levels) in execute'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/adapters/postgres.rb:520:in `check_database_errors'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/adapters/postgres.rb:323:in `block in execute'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/database/connecting.rb:250:in `block in synchronize'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/connection_pool/threaded.rb:85:in `hold'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/database/connecting.rb:250:in `synchronize'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/adapters/postgres.rb:323:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/database/query.rb:50:in `execute_dui'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/dataset/actions.rb:917:in `execute_dui'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/dataset/actions.rb:773:in `update'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:1952:in `_update_without_checking'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:1939:in `_update'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:1933:in `_update_columns'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:1881:in `block (2 levels) in _save'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:1124:in `around_update'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:1865:in `block in _save'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:1124:in `around_save'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:1848:in `_save'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:1528:in `block (2 levels) in save'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:2011:in `block in checked_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/database/transactions.rb:126:in `_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/database/transactions.rb:100:in `block in transaction'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/database/connecting.rb:250:in `block in synchronize'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/connection_pool/threaded.rb:98:in `hold'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/database/connecting.rb:250:in `synchronize'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/database/transactions.rb:89:in `transaction'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:2011:in `checked_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:1528:in `block in save'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:1999:in `checked_save_failure'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:1528:in `save'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:1541:in `save_changes'
/app/lib/shogun/heroku_resource.rb:109:in `update_from_response'
/app/lib/shogun/heroku_resource.rb:117:in `block in fetch'
/app/lib/shogun/metrics.rb:38:in `log_for_l2met'
/app/lib/shogun/heroku_resource.rb:113:in `fetch'
/app/lib/shogun/service.rb:36:in `ensure_heroku_resource'
/app/lib/shogun/resource.rb:1174:in `block in <class:Resource>'
/app/lib/shogun/state.rb:385:in `instance_eval'
/app/lib/shogun/state.rb:385:in `tick'
/app/lib/shogun/state.rb:178:in `block (3 levels) in tick'
/app/lib/shogun/metrics.rb:38:in `log_for_l2met'
/app/lib/shogun/state.rb:177:in `block (2 levels) in tick'
/app/lib/shogun/locker.rb:86:in `call'
/app/lib/shogun/locker.rb:86:in `with_lock'
/app/lib/shogun/locker.rb:93:in `with_lock'
/app/lib/shogun/state.rb:156:in `block in tick'
/app/vendor/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
/app/vendor/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `call'
/app/vendor/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
/app/lib/shogun/state.rb:149:in `tick'
/app/lib/shogun/state.rb:102:in `block in tick'
/app/lib/shogun/health.rb:50:in `context'
/app/lib/shogun/state.rb:100:in `tick'
/app/lib/shogun/worker.rb:14:in `perform'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/processor.rb:75:in `execute_job'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/chain.rb:127:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/app/lib/shogun/middleware/dyno_blacklist.rb:15:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/chain.rb:132:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/processor.rb:51:in `block in process'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/processor.rb:98:in `stats'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/processor.rb:50:in `process'
/app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
/app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

**Comment by jeremyevans** [comment] 2015-04-13 15:04
This backtrace is helpful, it shows that the problem must be in the literalization, not using the value as a bound variable.  As I mentioned earlier, Sequel just calls the `PGconn#escape_bytea` method for escaping the values, so if there are any problems with the literalization, those should really be in the `pg` driver, not in Sequel itself.

Alternatively, the input may not be as long as you expect it to be, but I'm assuming you are attempting to validate that before saving.  If not, it may be useful to add a validation for that.

You may want to try using the `prepared_statements` plugin in this model and see if that works around the issue.

**Comment by uhoh-itsmaciek** [comment] 2015-05-15 15:15
If anyone else ends up here, this led me to file [this bug against ruby-pg](https://bitbucket.org/ged/ruby-pg/issue/220/escape_bytea-not-safe-when-subclassing-pg).
