### ISSUE TITLE
When timeout occurs in Sequel::Database#transaction, the transaction is committed.

### ISSUE THREAD

**Issue by tmtm** [jeremyevans/sequel#1322] opened 2017-03-13 06:53 UTC
### Complete Description of Issue

When timeout occurs in Sequel::Database#transaction, the transaction is committed.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
require 'timeout'
require 'sequel'
require 'logger'

db = Sequel.connect('mysql2://user:password@localhost/test')
db.loggers = [Logger.new($stdout)]
Timeout.timeout(1) do
  db.transaction do
    db[:test].insert(id: 123)
    sleep 2
  end
end
```

```
I, [2017-03-13T15:37:24.942330 #2752]  INFO -- : (0.000113s) SET @@wait_timeout = 2147483
I, [2017-03-13T15:37:24.942475 #2752]  INFO -- : (0.000065s) SET SQL_AUTO_IS_NULL=0
I, [2017-03-13T15:37:24.942626 #2752]  INFO -- : (0.000051s) BEGIN
I, [2017-03-13T15:37:24.943035 #2752]  INFO -- : (0.000195s) INSERT INTO `test` (`id`) VALUES (123)
I, [2017-03-13T15:37:25.951336 #2752]  INFO -- : (0.009093s) COMMIT
/tmp/test-3.rb:10:in `sleep': execution expired (Timeout::Error)
        from /tmp/test-3.rb:10:in `block (2 levels) in <main>'
        from /tmp/gems/gems/sequel-4.44.0/lib/sequel/database/transactions.rb:215:in `_transaction'
        from /tmp/gems/gems/sequel-4.44.0/lib/sequel/database/transactions.rb:190:in `block in transaction'
        from /tmp/gems/gems/sequel-4.44.0/lib/sequel/database/connecting.rb:280:in `block in synchronize'
        from /tmp/gems/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
        from /tmp/gems/gems/sequel-4.44.0/lib/sequel/database/connecting.rb:280:in `synchronize'
        from /tmp/gems/gems/sequel-4.44.0/lib/sequel/database/transactions.rb:156:in `transaction'
        from /tmp/test-3.rb:8:in `block in <main>'
        from /usr/local/ruby24/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
        from /tmp/test-3.rb:7:in `<main>'
```

If an exception is raised in Sequel::Database#transaction block, the transaction is rolled back.
However, Timeout.timeout will not raise a Timeout::Error exception within the block, even if a timeout occurs.
It throws an exception object instead of raising an exception.
Therefore, the transaction is committed.

**Comment by janko-m** [comment] 2017-03-13 09:24
@tmtm There actually is nothing that the Sequel library can do to work around this, and that's the major flaw of the Timeout standard library. You see, `Timeout.timeout` spawns a new thread that starts executing whatever is in the block, but once the N seconds have run out, it calls `Thread#kill` on that thread. The limitation of `Thread#kill` is that it won't call any `ensure` blocks, it will just terminate the thread wherever it was left off.

The problem is that Ruby itself doesn't even have a way to terminate the thread in a way that it executes its `ensure` blocks, so it's not really an issue with the implementation of the Timeout library. See "[Ruby's Most Dangerous API](http://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/)" by Mike Perham for more details.

What you should do, instead of using the generic Timeout library, is to use the library-specific timeouts for any system calls, if it's available (and it usually is). In the case of Sequel, every database driver/adapter likely has an option of specifying the timeout at the driver-level, and the mysql2 driver itself has three kinds of timeouts: `:read_timeout`, `:write_timeout`, and `:connect_timeout`. So, if I'm not mistaken, the following should work:

```rb
require 'sequel'
require 'logger'

db = Sequel.connect('mysql2://user:password@localhost/test', :write_timeout: 1)
db.loggers = [Logger.new($stdout)]
db.transaction do
  db[:test].insert(id: 123) # if this command times out, transaction will be rolled back
  sleep 2
end
```

----

I just realized that if you instead put the `Timeout.timeout {}` call *inside* the the `db.transaction {}` call, it will also mean that your transaction will be rolled back, because the `Timeout::Error` would be raised from inside the `db.transaction {}` call, so the transaction can be rolled back.

```rb
db.transaction do
  Timeout.timeout(1) do
    db[:test].insert(id: 123)
    sleep 2
  end
end
```

However, in my opinion it's always better to use timeouts provided by the underlying library itself. For example, I could imagine that it's possible that by using `Timeout.timeout` the SQL command would still continue to be executed on the database, even though in Ruby-land a `Timeout::Error` was raised, while mysql2 could possibly really terminate the SQL command if it reached the timeout. I would definitely check that, because you want to make sure that slow SQL commands don't continue being executed if they were marked as "failed" by your Ruby application.

**Comment by jeremyevans** [comment] 2017-03-13 14:48
I agree with @janko-m that this is a bug in Timeout and not in Sequel.  It would be nice to handle Timeout since it is in the standard library, but I don't know of a way to examine the current throw value.   If Timeout used a static catch value, we could catch and rethrow to handle correctly.  Unfortunately, Timeout uses a separate Timeout::Error instance for each throw, without that information, I don't think this is possible.  You would have to modify Timeout::Error:

```ruby
class Timeout::Error
  def self.catch(*args)
    exc = new(*args)
    exc.instance_variable_set(:@thread, Thread.current)
    yield exc
  end

  def exception(*)
    if self.thread == Thread.current
      super(self)
    end
    self
  end
end
```

**Closed by jeremyevans** 2017-03-13 14:48 UTC

**Comment by nobu** [comment] 2017-03-14 05:04
You don't have to know the thrown value at all.
You should commit a transaction only when the given block finished successfully, instead of rolling back only at an exception.

**Comment by jeremyevans** [comment] 2017-03-14 14:47
@nobu That would break many applications that use Sequel.  Sequel expects that the transaction will be committed if using return or throw.  For example:

```ruby
def foo
  DB.transaction do
    model = Model.first
    model.update(:foo=>'bar')
    return unless model.bar
    model.bar.update(:baz=>'quux')
  end
end
```

or if using Sequel with Roda:

```ruby
  r.is "foo" do
    DB.transaction do
      model = Model.first
      model.update(:foo=>'bar')
      r.redirect model.redirect_to # uses throw internally
    end
  end
```

throw/catch should be used for control flow, raise/rescue for error handling, and a timeout is an error.  As far as I can see, the only reason Timeout uses throw/catch is so it does not raise an exception if there is no catch block for the specific Timeout::Error instance (it rescues `UncaughtThrowError`).  I can't see that happening without it being a bug in the user's code that should be fixed, where you would want an exception to be raised anyway.  I think Timeout should be fixed.

FWIW, ActiveRecord appears to handle things the same way, only rolling back transactions on exception (the only sensible behavior IMO): https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L184

**Comment by smostovoy** [comment] 2019-03-25 11:48
you can pass an error class and it will be rescuable. I had the same problem with active record.
e.g. `Timeout.timeout(1, Timeout::Error) do` 
`The exception thrown to terminate the given block cannot be rescued inside the block unless klass is given explicitly.`
https://ruby-doc.org/stdlib-2.4.0/libdoc/timeout/rdoc/Timeout.html
