### ISSUE TITLE
MS Access create table throws method_missing Exception when column has a default value

### ISSUE THREAD

**Issue by mdavis1960** [jeremyevans/sequel#1748] opened 2021-01-24 23:52 UTC
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue

in MS Access when I create a new table with a column that provides a default value, I get a method_missing exception.  If I remove the default value, it will create the table as expected.  The commented out sql variables work in both WIN32OLE and Sequel.  The uncommented sql works in WIN32OLE and throws and exception in Sequel.

This is not a priority for me, I just bumped into while testing some unrelated code.

### Simplest Possible Self-Contained Example Showing the Bug

  require 'win32ole'
  filename = 'c:\\temp\\northwind.mdb'
  #sql = "CREATE TABLE [Products1] ([ProductID] INTEGER NOT NULL, [ProductName] VARCHAR(40) NOT NULL, [UnitsInStock] SMALLINT NULL, [Discontinued] BIT NOT NULL, PRIMARY KEY ([ProductID]))"
  sql = "CREATE TABLE [Products1] ([ProductID] INTEGER NOT NULL, [ProductName] VARCHAR(40) NOT NULL, [UnitsInStock] SMALLINT DEFAULT 0 NULL, [Discontinued] BIT DEFAULT 0 NOT NULL, PRIMARY KEY ([ProductID]))"
  File.delete(filename) if File.exists?(filename)
  connection_string = { adapter: :ado, conn_string: "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=#{filename}" }
  conn = WIN32OLE.new("ADOX.Catalog")
  conn.create(connection_string[:conn_string])
  conn = WIN32OLE.new("ADODB.Connection")	# works
  conn.open(connection_string[:conn_string])
  conn.close
  
  #sql = "CREATE TABLE [Products2] ([ProductID] INTEGER NOT NULL, [ProductName] VARCHAR(40) NOT NULL, [UnitsInStock] SMALLINT NULL, [Discontinued] BIT NOT NULL, PRIMARY KEY ([ProductID]))"
  sql = "CREATE TABLE [Products2] ([ProductID] INTEGER NOT NULL, [ProductName] VARCHAR(40) NOT NULL, [UnitsInStock] SMALLINT DEFAULT 0 NULL, [Discontinued] BIT DEFAULT 0 NOT NULL, PRIMARY KEY ([ProductID]))"
  Sequel.connect(connection_string) do |db|
  db.execute(sql)
  end

### Full Backtrace of Exception (if any)

C:/Ruby27/lib/ruby/gems/2.7.0/gems/sequel-5.39.0/lib/sequel/adapters/ado.rb:162:in `method_missing': WIN32OLERuntimeError: (in OLE method `Execute': ) (Sequel::DatabaseError)
    OLE error code:80040E14 in Microsoft Access Database Engine
      Syntax error in CREATE TABLE statement.
    HRESULT error code:0x80020009
      Exception occurred.
        from C:/Ruby27/lib/ruby/gems/2.7.0/gems/sequel-5.39.0/lib/sequel/adapters/ado.rb:162:in `block (2 levels) in execute'
        from C:/Ruby27/lib/ruby/gems/2.7.0/gems/sequel-5.39.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
        from C:/Ruby27/lib/ruby/gems/2.7.0/gems/sequel-5.39.0/lib/sequel/adapters/ado.rb:162:in `block in execute'
        from C:/Ruby27/lib/ruby/gems/2.7.0/gems/sequel-5.39.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
        from C:/Ruby27/lib/ruby/gems/2.7.0/gems/sequel-5.39.0/lib/sequel/database/connecting.rb:269:in `synchronize'
        from C:/Ruby27/lib/ruby/gems/2.7.0/gems/sequel-5.39.0/lib/sequel/adapters/ado.rb:160:in `execute'
        from tools/test.rb:264:in `block in test_access_default_bug'
        from C:/Ruby27/lib/ruby/gems/2.7.0/gems/sequel-5.39.0/lib/sequel/database/connecting.rb:59:in `connect'
        from C:/Ruby27/lib/ruby/gems/2.7.0/gems/sequel-5.39.0/lib/sequel/core.rb:124:in `connect'
        from tools/test.rb:263:in `test_access_default_bug'
        from tools/test.rb:268:in `<main>'
C:/Ruby27/lib/ruby/gems/2.7.0/gems/sequel-5.39.0/lib/sequel/adapters/ado.rb:162:in `method_missing': (in OLE method `Execute': ) (WIN32OLERuntimeError)
    OLE error code:80040E14 in Microsoft Access Database Engine
      Syntax error in CREATE TABLE statement.
    HRESULT error code:0x80020009
      Exception occurred.
        from C:/Ruby27/lib/ruby/gems/2.7.0/gems/sequel-5.39.0/lib/sequel/adapters/ado.rb:162:in `block (2 levels) in execute'
        from C:/Ruby27/lib/ruby/gems/2.7.0/gems/sequel-5.39.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
        from C:/Ruby27/lib/ruby/gems/2.7.0/gems/sequel-5.39.0/lib/sequel/adapters/ado.rb:162:in `block in execute'
        from C:/Ruby27/lib/ruby/gems/2.7.0/gems/sequel-5.39.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
        from C:/Ruby27/lib/ruby/gems/2.7.0/gems/sequel-5.39.0/lib/sequel/database/connecting.rb:269:in `synchronize'
        from C:/Ruby27/lib/ruby/gems/2.7.0/gems/sequel-5.39.0/lib/sequel/adapters/ado.rb:160:in `execute'
        from tools/test.rb:264:in `block in test_access_default_bug'
        from C:/Ruby27/lib/ruby/gems/2.7.0/gems/sequel-5.39.0/lib/sequel/database/connecting.rb:59:in `connect'
        from C:/Ruby27/lib/ruby/gems/2.7.0/gems/sequel-5.39.0/lib/sequel/core.rb:124:in `connect'
        from tools/test.rb:263:in `test_access_default_bug'
        from tools/test.rb:268:in `<main>'

**Comment by jeremyevans** [comment] 2021-01-25 02:55
I'll try reproducing this tomorrow, but as the error is an SQL syntax error (`Syntax error in CREATE TABLE statement.`) from SQL not produced by Sequel, it doesn't look like there is anything I'm going to be able to do.

**Comment by jeremyevans** [comment] 2021-01-29 18:50
Sorry for the delay.  I tried your SQL code and it fails for me both using Sequel and using `ADODB.Connection` directly.  If you look at your example, you are not running the sql when using `ADODB.Connection` directly.  You can run `conn.execute(sql)` before `conn.close` in your earlier example and you should get the same failure:

```
irb(main):009:0> conn.execute(sql)
Traceback (most recent call last):
        3: from C:/Ruby25-x64/bin/irb.cmd:19:in `<main>'
        2: from (irb):9
        1: from (irb):9:in `method_missing'
WIN32OLERuntimeError ((in OLE method `execute': )
    OLE error code:80040E14 in Microsoft Access Database Engine
      Syntax error in CREATE TABLE statement.
    HRESULT error code:0x80020009
      Exception occurred.)
```

Since this doesn't appear to be a Sequel issue, I'm going to close this now.

**Closed by jeremyevans** 2021-01-29 18:50 UTC
