### ISSUE TITLE
`in_transaction?` sometimes attempts to make a connection.

### ISSUE THREAD

**Issue by alexf101** [jeremyevans/sequel#1661] opened 2019-11-08 23:40 UTC
If you call `db.in_transaction?` on a Sequel::Mysql2::Database, and it has no open connections, it forms a connection instead of immediately returning `false`. This is due to its use of `synchronize` to get hold of the current connection. In ordinary circumstances, `in_transaction?` is basically free in that it only checks client-side metadata about the connection.

This caused a problem in our deployment when we added a mostly-unused read replica. For _reasons_, our rpc framework checks to see if we are in a transaction before making a call. This went from being an essentially free check since almost all of our micro-services had a database connection already open, to an expensive database connection that caused unnecessary downtime when our replica was offline for a minute.

If the current thread has no connection, I don't see why `in_transaction?` shouldn't simply return `false` without making a new connection.

We've implemented our own wrapper to solve our immediate problem, but I expect that it's an issue that could easily affect others, so an upstream solution would be much appreciated. I'm happy to send a PR if you agree on the premise.

We are using MySQL and threaded connection pool, Sequel 5.20.

**Comment by jeremyevans** [comment] 2019-11-09 00:02
I think the issue with making `in_transaction?` not checkout a connection is that you need to modify the connection pool in order to do that.  The Database instance doesn't know whether there are open connections, only the connection pool does.  Sequel supports user-specified connection pool classes, so adding a method to connection pool changes the connection pool <-> Database API, potentially requiring user-specified connection pool classes to be modified.

Additionally, by having `in_transaction?` check with the connection pool, that will make calling the method slower, and it is a rare situation to have `in_transaction?` be called without an open connection.

It seems odd to add this to solve downtime issues where a read-replica is down, considering any queries using the Database at that point would also result in downtime issues.

I think the best way to solve this would be to implement the support as a Database extension (see the `connection_validator` and `connection_expiration` extensions as examples).  That way, only the people that need this support would have to use it.  I'm not sure whether there is a significant need for shipping such an extension with Sequel, but you could ask on the sequel-talk Google Group and get community feedback for it.  I'm willing to consider shipping such an extension with Sequel if there is community demand for it.

The current behavior is expected and not a bug, so I'm going to close this.

**Closed by jeremyevans** 2019-11-09 00:02 UTC
