### ISSUE TITLE
modification_detection plugin is broken?

### ISSUE THREAD

**Issue by tycooon** [jeremyevans/sequel#1468] opened 2018-01-20 09:54 UTC
### Complete Description of Issue
It seems like modification_detection (and I think serialization_modification_detection as well) is completely broken in sequel 5.4.0. The problem is that it modifies the `changed_columns` method to dynamically return an array, however there is a lot of stuff like `changed_columns << smth` throughout the code.

### Simplest Possible Self-Contained Example Showing the Bug
```ruby
x = Model.new
x.foo = "new value"
x.changed_columns # => []
```

**Comment by jeremyevans** [comment] 2018-01-20 16:58
This does appear to be a bug in `modification_detection`.  It should operate like `serialization_modification_detection` and return a modified array, not a new array.  I'll work on a fix shortly.

**Comment by jeremyevans** [comment] 2018-01-20 17:25
I have a fix for this that I'm currently testing.  The reason this wasn't caught previously is that it is only broken on new objects, and for those `changed_columns` is basically ignored since all columns are saved.  It could probably also affect retrievals of existing objects where you only select a subset of the model's columns, then set a value for a column you didn't select.

**Closed** 2018-01-20 17:26 UTC

**Comment by tycooon** [comment] 2018-01-21 12:39
Just one note: the bug was true not only for unsaved objects, but for created ones as well. Basically updating the newly created object was broken until that fix:

```ruby
x = SomeModel.create(a: 1)
x.update(a: 2) # not working
```

You may consider releasing that bugfix as a new gem version.

**Comment by jeremyevans** [comment] 2018-01-21 17:49
New gems are only released for bug fixes if the bug fix is a regression in the most recent release.  So if the bug appears in 5.4.0 but it was working in 5.3.0, then it would be a candidate for a 5.4.1 release.  I don't believe that is true in this case.
