### ISSUE TITLE
read-only slaves help

### ISSUE THREAD

**Issue by austinthecoder** [jeremyevans/sequel#1419] opened 2017-09-19 17:37 UTC
My setup is the "Multiple Read-Only Slaves, Single Master" approach, outlined here:
https://github.com/jeremyevans/sequel/blob/master/doc/sharding.rdoc

I have one master and four slaves. The first two slaves seem to be getting the vast majority of traffic. Here's a screenshot of the RDS activity:

![screen shot 2017-09-19 at 1 35 13 pm](https://user-images.githubusercontent.com/4664/30606355-77b06b1a-9d3f-11e7-9b00-dbd00f3706b2.png)

Here's my code:

```ruby
read_host_index = 0

read_only_proc = ->(_) do
  read_host_index = (read_host_index += 1) % 4
  host = READ_DB_HOSTS[read_host_index]
  {host: host}
end

Sequel.connect WRITE_DB_URL, servers: {read_only: read_only_proc}
```

Does that look correct? Any idea why it's not balancing?

**Comment by jeremyevans** [comment] 2017-09-19 18:13
It's hard to say exactly why without a self-contained example.  My first guess would be that connections are only created as needed, so there is probably an unequal number of connections to the database servers? You can try the Database :preconnect option if that is the case, or set `read_host_index = rand(4)` at the top if you are running this on many servers.

Disconnects can affect how many connections are used for each server. I'm not sure what Sequel version is used, but old versions of Sequel used a stack instead of a queue for connection handling, so that the most recently used connection was used first.  Seems unlikely you would be on a version that old, though.

There are probably a number of other reasons that would cause it not to balance, so producing a minimal self-contained example showing the problem is going to be the first step.

Since this is a help request and not a bug report (yet), you should probably post more details (including a self-contained example) on the sequel-talk Google Group.  GitHub Issues should only be used for reporting bugs in Sequel, as mentioned in the contribution guidelines.  I'm going to close this now, if after discussion on sequel-talk, it appears to be a bug in Sequel, this can be reopened.

**Closed by jeremyevans** 2017-09-19 18:13 UTC

**Comment by austinthecoder** [comment] 2017-09-19 18:41
Changing from round-robin to random did the trick!

![screen shot 2017-09-19 at 2 39 10 pm](https://user-images.githubusercontent.com/4664/30609093-6ba55d18-9d48-11e7-8245-b82b8ed6b5de.png)

Thank you for the fast response. I'll check out the Google Group. We use sequel a lot with heavy traffic and it's been great.
