### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by calh** [jeremyevans/sequel#1706] opened 2020-08-04 15:40 UTC
### Complete Description of Issue

I've searched around for other solutions to this problem, and I could only find bug reports that are 9 years old.  When I have a burst of concurrency in my Sinatra app, it throws an exception `Sequel::DatabaseDisconnectError - Mysql2::Error::ConnectionError: MySQL server has gone away`.  After that, it seems to be stuck, and no queries succeed.  The sinatra app hangs for a long time and eventually returns the error message up the stack.

During this event, I also do not see any connection spikes on the mysql server.  The `wait_timeout` on the server is set to 60 seconds.

### Simplest Possible Self-Contained Example Showing the Bug

Mysql = Sequel.connect(settings.mysql_slave)
Mysql.extension(:connection_validator)
Mysql.pool.connection_validation_timeout = 40
(Run a query after this)

### Full Backtrace of Exception (if any)
```
App 93370 output: 2020-08-04 09:43:06 - Sequel::DatabaseDisconnectError - Mysql2::Error::ConnectionError: MySQL server has gone away:
App 93370 output:       /prod/shared/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'
App 93370 output:       /prod/shared/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
App 93370 output:       /prod/shared/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
App 93370 output:       /prod/shared/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
App 93370 output:       /prod/shared/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/adapters/mysql2.rb:136:in `block in _execute'
App 93370 output:       /prod/shared/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
App 93370 output:       /prod/shared/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/adapters/mysql2.rb:131:in `_execute'
App 93370 output:       /prod/shared/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/adapters/utils/mysql_mysql2.rb:39:in `block in execute'
App 93370 output:       /prod/shared/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
App 93370 output:       /prod/shared/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/database/connecting.rb:270:in `synchronize'
App 93370 output:       /prod/shared/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/adapters/utils/mysql_mysql2.rb:39:in `execute'
App 93370 output:       /prod/shared/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/dataset/actions.rb:1089:in `execute'
App 93370 output:       /prod/shared/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/adapters/mysql2.rb:276:in `execute'
App 93370 output:       /prod/shared/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/adapters/mysql2.rb:236:in `fetch_rows'
App 93370 output:       /prod/shared/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/dataset/actions.rb:942:in `with_sql_each'
App 93370 output:       /prod/shared/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/dataset/actions.rb:950:in `with_sql_first'
App 93370 output:       /prod/shared/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/dataset/actions.rb:958:in `with_sql_single_value'
App 93370 output:       /prod/shared/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/dataset/actions.rb:730:in `single_value!'
App 93370 output:       /prod/shared/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/dataset/actions.rb:166:in `empty?'
App 93370 output:       /prod/releases/20200803202013/lib/routes/portal.rb:8:in `block in registered'
```

### SQL Log (if any)

(none)

**Comment by jeremyevans** [comment] 2020-08-04 15:50
The error is correctly raised as a DatabaseDisconnectError, which will cause the connection pool to remove the connection and a new connection to be made when a connection is requested from the pool (if there are no other connections available in the pool).  I'm not sure what would cause the app to be stuck.  Can you provide a self contained reproducible example showing your issue?

**Comment by calh** [comment] 2020-08-04 16:04
The app code in portal.rb is pretty simple, it's just running a query off the `Mysql` object.  I want to redact this a bit for security reasons, but let me know if you need more details.  The general pseudocode of what I'm doing is:

```
dataset = Mysql[:table].where(...).limit(1)
if dataset.empty?
  return not found error
else
  return dataset.first[:timestamp].strftime(TIME_FORMAT)
end
```

The `MySQL server has gone away` comes from the `empty?` call, but subsequent hits are falling into the `else` case and showing a result package which seems to have no fields:

```App 101142 output: 2020-08-04 10:11:08 - NoMethodError - undefined method `strftime' for nil:NilClass:
App 101142 output:      prod/releases/20200804145115/lib/routes/portal.rb:12:in `block in registered'
App 101142 output:      prod/shared/bundle/ruby/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `call'
```

I haven't yet been able to easily recreate this in an isolated test case.  It seems to only happen when I give the servers production traffic.

**Comment by jeremyevans** [comment] 2020-08-04 16:11
`Dataset#empty?` shouldn't rescue any exceptions, so I'm not sure how the else block would be executed if an exception was raised by `empty?`.

For the NoMethodError, it could occur if the dataset was not empty, but the timestamp value for the row returned was nil.  I'm not sure that is what is causing it, but it is a possibility.  Are you sure that the `dataset.first` call in the else block returns `{}`?

Without a self contained reproducible example, there isn't much I can do to help you.  So if you are unable to create one, I'll probably have to close this.

**Comment by calh** [comment] 2020-08-04 16:14
I'll work on some extra logging and try to come up with a method to recreate this.

**Comment by calh** [comment] 2020-08-04 17:10
Okay here's a simple recreation that you could use against any server:

Gemfile:
```
source "https://rubygems.org"

gem 'sequel', '5.31.0'
gem 'mysql2', '0.5.2'
```

test.rb:
````
require 'sequel'
require 'mysql2'
Mysql = Sequel.connect('mysql2://...')
Mysql.extension(:connection_validator)
Mysql.pool.connection_validation_timeout = 40

# Get my own ID for this connection
my_id = 0
Mysql.fetch("select * from information_schema.processlist") do |row|
  if row[:INFO] =~ /information_schema\.processlist/
    my_id = row[:ID]
  end
end
puts "my_id: #{my_id}"

# Kill it
Mysql.run("KILL #{my_id}")

dataset = Mysql.fetch("select 1")

puts "Dataset: #{dataset.inspect}"
if dataset.empty?
  puts "Dataset EMPTY"
else
  puts "Dataset not empty"
end
```

```
$ bundle exec ruby test.rb 
my_id: 24489752
Dataset: #<Sequel::Mysql2::Dataset: "select 1">
Traceback (most recent call last):
        19: from test.rb:22:in `<main>'
        18: from mysqltest/vendor/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/dataset/actions.rb:166:in `empty?'
        17: from mysqltest/vendor/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/dataset/actions.rb:730:in `single_value!'
        16: from mysqltest/vendor/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/dataset/actions.rb:958:in `with_sql_single_value'
        15: from mysqltest/vendor/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/dataset/actions.rb:950:in `with_sql_first'
        14: from mysqltest/vendor/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/dataset/actions.rb:942:in `with_sql_each'
        13: from mysqltest/vendor/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/adapters/mysql2.rb:236:in `fetch_rows'
        12: from mysqltest/vendor/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/adapters/mysql2.rb:276:in `execute'
        11: from mysqltest/vendor/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/dataset/actions.rb:1089:in `execute'
        10: from mysqltest/vendor/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/adapters/utils/mysql_mysql2.rb:39:in `execute'
         9: from mysqltest/vendor/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/database/connecting.rb:270:in `synchronize'
         8: from mysqltest/vendor/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
         7: from mysqltest/vendor/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/adapters/utils/mysql_mysql2.rb:39:in `block in execute'
         6: from mysqltest/vendor/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/adapters/mysql2.rb:131:in `_execute'
         5: from mysqltest/vendor/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
         4: from mysqltest/vendor/bundle/ruby/2.5.0/gems/sequel-5.31.0/lib/sequel/adapters/mysql2.rb:136:in `block in _execute'
         3: from mysqltest/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
         2: from mysqltest/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
         1: from mysqltest/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
mysqltest/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query': Mysql2::Error::ConnectionError: MySQL server has gone away (Sequel::DatabaseDisconnectError)
```

**Comment by calh** [comment] 2020-08-04 17:15
Also in testing the latest versions, sequel 5.35.0 and mysql2 0.5.3 the same error happens.

**Comment by calh** [comment] 2020-08-04 17:26
If I change `Mysql.pool.connection_validation_timeout` to `-1` the test case succeeds.  So I guess my bigger question -- can Sequel retry a query that fails, rather than perform a connection check on every query?

**Comment by jeremyevans** [comment] 2020-08-04 17:48
Sequel does not retry queries as it in general is not safe to do so.  There is a :retry_on option to Database#transaction, which you can use if you are sure that the transaction block is idempotent.

Your example shows an issue with Sequel in my environment, in that it brings up a error that was not raised as a disconnect error (maybe it is specific to MariaDB?). I'll commit a fix for that shortly.

It is expected that if there is a disconnect error, it will be raised to the user code.  The connection will be removed from the pool and a new one will be created when needed.

It's only considered a bug in Sequel if the connection is unusable after the error is raised.  In those cases, Sequel should treat the error as a disconnect error, and remove the connection from the pool.

I modified your example slightly to show Sequel's expected behavior:

```ruby
require 'sequel'
require 'logger'

Mysql = Sequel.connect(ENV['DATABASE_URL'], :logger=>Logger.new($stdout))
Mysql.extension(:connection_validator)
Mysql.pool.connection_validation_timeout = 40

# Get my own ID for this connection
my_id = 0
Mysql.fetch("select * from information_schema.processlist") do |row|
  if row[:INFO] =~ /information_schema\.processlist/
    my_id = row[:ID]
  end
end
puts "my_id: #{my_id}"

# Kill it
begin
  Mysql.run("KILL #{my_id}")
rescue => e
  p e
end

dataset = Mysql.fetch("select 1")

begin
  puts "Dataset: #{dataset.inspect}"
  if dataset.empty?
    puts "Dataset EMPTY"
  else
    puts "Dataset not empty"
  end
rescue => e
  p e
end

puts dataset.empty?
```

This results in the output (with the patch that I will commit shortly):

```
I, [2020-08-04T10:35:27.837286 #83766]  INFO -- : (0.003381s) SET @@wait_timeout = 2147483
I, [2020-08-04T10:35:27.837804 #83766]  INFO -- : (0.000130s) SET SQL_AUTO_IS_NULL=0
I, [2020-08-04T10:35:27.840569 #83766]  INFO -- : (0.001291s) SELECT version()
I, [2020-08-04T10:35:27.844753 #83766]  INFO -- : (0.000186s) SELECT version()
I, [2020-08-04T10:35:27.849534 #83766]  INFO -- : (0.004533s) select * from information_schema.processlist
my_id: 589
E, [2020-08-04T10:35:27.854544 #83766] ERROR -- : Mysql2::Error: Connection was killed: KILL 589
#<Sequel::DatabaseDisconnectError: Mysql2::Error: Connection was killed>
Dataset: #<Sequel::Mysql2::Dataset: "select 1">
I, [2020-08-04T10:35:27.856804 #83766]  INFO -- : (0.000123s) SET @@wait_timeout = 2147483
I, [2020-08-04T10:35:27.857016 #83766]  INFO -- : (0.000123s) SET SQL_AUTO_IS_NULL=0
I, [2020-08-04T10:35:27.857404 #83766]  INFO -- : (0.000267s) select 1
Dataset not empty
I, [2020-08-04T10:35:27.857790 #83766]  INFO -- : (0.000198s) select 1
false
```

You can see from the log that after the connection is killed, a new connection is created (it sets the wait_timeout and SQL_AUTO_IS_NULL on connection).

**Comment by calh** [comment] 2020-08-04 18:02
Thanks!  I'd like to find a method to retry 5 times, like in the transaction logic.  I'm kind of fumbling with the syntax though, does this look correct?

```
dataset = Mysql.transaction(retry_on: Mysql2::Error::ConnectionError) { Mysql.fetch("select 1") }
```

That still throws an exception.

**Comment by jeremyevans** [comment] 2020-08-04 18:04
That's because the exception raised is not `Mysql2::Error::ConnectionError`, but `Sequel::DatabaseDisconnectError`.

**Comment by calh** [comment] 2020-08-04 18:05
Bingo!  Thanks for your help!

**Closed** 2020-08-04 18:05 UTC
