### ISSUE TITLE
Sequel::Model.plugin :insert_conflict invalid lifecycle

### ISSUE THREAD

**Issue by PetrKaleta** [jeremyevans/sequel#1871] opened 2022-05-13 13:01 UTC
Sequel version `5.56.0`

There's is an issue with `insert_conflict` Sequel::Model plugin. Please have a look on following code:

```ruby
# Model table schema:
#
#   create_table(:foos) do
#     column :id, 'uuid', default: Sequel::LiteralString.new('uuid_generate_v4()'), null: false
#     column :code, 'character varying(7)', null: false
#     column :name, 'character varying(128)', null: false
#     column :description, 'text'
#
#     primary_key [:id]
#
#     index [:code], unique: true
#   end
#
class Foo < Sequel::Model(:foos)
  plugin :insert_conflict

  def after_create
    super

    puts 'Foo model created'
  end
end

Foo.new(code: 'A', name: 'This is a').insert_conflict(target: :code).save # this will create an entry
Foo.new(code: 'A', name: 'This is a').insert_conflict(target: :code).save # this will not create an entry
```

The first issue I've found is, that `after_create` hook is called no matter if the new instance was created or not.

Second issue I've found is, that it is raising an `Sequel::NoExistingObject (Record not found)` error when adding `lazy_attributes` plugin:

```ruby
# Model table schema:
#
#   create_table(:foos) do
#     column :id, 'uuid', default: Sequel::LiteralString.new('uuid_generate_v4()'), null: false
#     column :code, 'character varying(7)', null: false
#     column :name, 'character varying(128)', null: false
#     column :description, 'text'
#
#     primary_key [:id]
#
#     index [:code], unique: true
#   end
#
class Foo < Sequel::Model(:foos)
  plugin :insert_conflict
  plugin :lazy_attributes, :description
end

Foo.new(code: 'B', name: 'This is b').insert_conflict(target: :code).save # this will create an entry
Foo.new(code: 'B', name: 'This is b').insert_conflict(target: :code).save # this will raise an Sequel::NoExistingObject (Record not found) error

**Comment by jeremyevans** [comment] 2022-05-13 16:03
I think the real bug here is that the insert_conflict plugin documentation does not warn you that you should not use it to ignore conflicts, and that it should only be used to turn INSERT conflicts into UPDATEs.  So I'll fix that shortly. For what you are doing, you should not use Model#save for the ignored insert, you should use a dataset insert.

The first issue is expected and not a bug. `after_create` is called if the INSERT succeeds, and by using `insert_conflict`, you are making the INSERT succeed even if it doesn't modify the database.  On PostgreSQL, if you are not setting the the primary key  before saving the object, you can use this approach:

```ruby
  def after_create
    super

    puts 'Foo model created' if id
  end
```

The second issue is related to how Sequel handles an INSERT that doesn't return a value, when the model has a primary key but the model object being saved does not have a value for the primary key.  Let me be clear that such a model object is broken at that point.  I have a patch that will make it so the Sequel::NoExistingObject error is not raised immediately:

```diff
diff --git a/lib/sequel/model/base.rb b/lib/sequel/model/base.rb
index 8593eed56..7525c8d6f 100644
--- a/lib/sequel/model/base.rb
+++ b/lib/sequel/model/base.rb
@@ -1712,10 +1712,9 @@ module Sequel
           iid = _insert_raw(ds)
           # if we have a regular primary key and it's not set in @values,
           # we assume it's the last inserted id
-          if (pk = autoincrementing_primary_key) && pk.is_a?(Symbol) && !(vals = @values)[pk]
-            vals[pk] = iid
+          if (pk = autoincrementing_primary_key) && pk.is_a?(Symbol)
+            @values[pk] ||= iid
           end
-          pk
         end
       end

```

However, I don't think it should be committed, because it hides the underlying issue.  After being saved, model objects are expected to have a primary key value, and if they don't, things break. Calling `description` on the returned object in your example will not work, because it relies on having the primary key value.  Trying to save the object a second time will not work for the same reason.  Such a patch delays detection of the underlying problem, and I don't think that's a good thing.

**Closed** 2022-05-13 16:03 UTC

**Comment by PetrKaleta** [comment] 2022-05-23 09:15
Hi Jeremy,
I totally understand your point, but maybe there's still a valid point for a discussion. As you said, your `insert_conflict` plugin should not be used to ignore conflicts (as it is designed) but it seems that `ON CONFLICT ON CONSTRAINT constraint_name DO NOTHING` is an ideal way to handle creation of objects with unique key. Why?

I'll try to explain it on a simple example:

```ruby
def find_or_create(code:, name:)
  db.transaction(savepoint: :only) do
    create(code: code, name: name)
  rescue Sequel::UniqueConstraintViolation
    raise Sequel::Rollback if db.in_transaction?
  end || first(code: code)
end
```

Currently I am using this approach. It works as expected, but with two huge downsides:
1. You can't control which column raised `UniqueConstraintViolation`
2. Each time UniqueConstraintViolation is raised, Postgres automatically logs this operation as DB error (so your DB log is then full of this errors)

Both of this problems can be solved very easily with `ON CONFLICT ON CONSTRAINT constraint_name DO NOTHING` approach. Yes, you can implement this functionality directly od dataset, but you'll loose all the benefits of using model:

1. model validations
2. model hooks
3. model plugins

What I am suggesting is the following implementation (please continue with example from my original post):

```ruby
# Model table schema:
#
#   create_table(:foos) do
#     column :id, 'uuid', default: Sequel::LiteralString.new('uuid_generate_v4()'), null: false
#     column :code, 'character varying(7)', null: false
#     column :name, 'character varying(128)', null: false
#
#     primary_key [:id]
#
#     index [:code], unique: true
#   end
#
class Foo < Sequel::Model(:foos)
  plugin :insert_conflict
end

foo = Foo.new(code: 'A', name: 'This is a').insert_conflict(target: :code)
foo.save # no conflict, creates new entry, all hooks should be called as expected
foo.new? # => false

conflicted_foo = Foo.new(code: 'A', name: 'This is a').insert_conflict(target: :code)
conflicted_foo.save # as there's existing entry with code `A`, then all hooks should be ignored (same way like when there's a validation error) and the conflicted_foo should still behave as a `new?`
conflicted_foo.new? # => true

# maybe we can go even further and create an error on column `code`, because we know, that it is not unique...
conflicted_foo.valid? # => false
conflicted_foo.errors[:code] # => "is not unique (insert conflict)"
```

It will be even better if we can extend `insert_conflict` method with additional attribute called `on_conflict` so:

```ruby
foo = Foo.new(code: 'A', name: 'This is a')
foo.insert_conflict(target: :code, on_conflict: :raise).save # this will raise Sequel::InsertConflictError
foo.insert_conflict(target: :code, on_conflict: { update: { ... } }).save # this will do an update
```

Maybe I am wrong, but this seems to be like an ideal way to solve model creation while still having all the benefits of using models... What do you think?
