### ISSUE TITLE
Connects to Snowflake but crashes when querying

### ISSUE THREAD

**Issue by ccoffey** [jeremyevans/sequel#2114] opened 2024-01-04 17:02 UTC
### Complete Description of Issue

I have added the following two gems (latest versions of each) to my Gemfile:
```ruby
gem "sequel", "5.76.0"
gem "ruby-odbc", "0.999991" # Seems to be necessary to use Sequel.odbc
```

Then on a Rails console, it looks like I can connect (because it takes a second) but then it crashes when I try to query:

```ruby
connection_str = [
  'DRIVER=/opt/snowflake/snowflakeodbc/lib/universal/libSnowflake.dylib;',
  'SERVER=<account>.snowflakecomputing.com;',
  'UID=<uid>;',
  'PWD=<pwd>;',
].join('')

db = Sequel.odbc(drvconnect: connection_str)
=> #<Sequel::ODBC::Database: {:adapter=>:odbc, :drvconnect=>"...

db.fetch("select current_version();").all
[1]    14340 abort      rails c
```

Seems to crash if I execute any query, for example:
```ruby
db["select 1;"].count
[1]    14798 abort      rails c
```

How do I debug this? Are there logs I can look at? I see nothing on the console before it crashes.

I've verified that I can connect using `iodbctest` and the same config:
```
Enter ODBC connect string (? shows list): dsn=testodbc1;pwd=<REDACTED>
Driver: 3.1.4 (Snowflake)

SQL>SELECT 1;

1
---
1

 result set 1 returned 1 rows.
```

Any help would be very much appreciated

### Ruby Version

ruby 3.1.4p223

### Sequel Version

5.76.0

**Comment by jeremyevans** [comment] 2024-01-04 17:28
Sequel itself contains no native code.  If you are getting a segfault/crash, it is a bug in the ruby-odbc native code or the underlying ODBC driver (or Ruby itself, but that seems unlikely in this case).  You'll probably need to run the code under a C debugger such as gdb to track down the issue.  Based on https://github.com/vendasta/sequel-snowflake/issues/16#issuecomment-1828471244, this appears to be a recently introduced bug in unixODBC, as downgrading unixODBC to 2.3.11 fixed the issue.  Closing as this does not appear to be a bug in Sequel.

**Closed by jeremyevans** 2024-01-04 17:28 UTC

**Comment by ccoffey** [comment] 2024-01-04 17:41
@jeremyevans you are likely correct, but I did tried the following:
```
gem uninstall ruby-odbc
gem install ruby-odbc -- --with-odbc-dir=/opt/homebrew/Cellar/unixodbc/2.3.11
```

However, I am still seeing the same crash 🤔 Any suggestions?

**Comment by jeremyevans** [comment] 2024-01-04 17:57
Unfortunately, I don't have any other than my previous suggestion of running it under gdb (maybe lldb would work as well) and seeing where the crash occurs.  I haven't actually tested Sequel's odbc adapter with unixodbc (I test the Sequel odbc adapter on Windows), though I have had reports that it works.

**Comment by AdamFreemer** [comment] 2025-02-21 01:25
@ccoffey @jeremyevans Hey guys. Just was curious if anyone has worked further on this issue? I'm having the same crash:
```
[3] pry(main)> conn = Sequel.odbc(odbc_name, user: username, password: password)
=> #<Sequel::ODBC::Database database=snowflake user=OASPAPI_ETL_DEV>
[4] pry(main)> conn.run("LIST TABLES")
[1]    2176 abort      rails c
```
Ruby 3.3.5, OS 15.3.1, latest version of ruby-odbc and sequel gems. 

I confirmed my code works on a Red Hat machine (one of my production servers). So it's very specific to my local mac setup and seems to be the same issue experienced above. 

@jeremyevans I wasn't able to successfully build / make unixodbc 2.3.11 to test if that works (and obviously not available through brew install). Any other ideas extremely welcome!

**Comment by jeremyevans** [comment] 2025-02-21 01:53
The only new suggestion I could offer would be to see if there is a JDBC driver you could use, and use JRuby and Sequel's jdbc adapter.  However, that assumes that the rest of the application could work with JRuby, which may not be the case.
