### ISSUE TITLE
Sequel::Model#save( raises_on_failure: false ) still raises exception

### ISSUE THREAD

**Issue by deemytch** [jeremyevans/sequel#1749] opened 2021-01-28 09:26 UTC
sequel 5.40.0
ruby 2.7.2p137
archlinux

Tested model with flag in class and function parameter, `raises_on_failure = false` just not working.
It raises exception not regarding to that option.
rspec test, migration files and postgres listing attached.

So that code raises error:
```
Sequel::Model.raise_on_save_failure = false
m = SomeModel.new( incorrect_params )
m.save( raise_on_failure: false )
```

[sequel-testing.tar.gz](https://github.com/jeremyevans/sequel/files/5886071/sequel-testing.tar.gz)

**Comment by jeremyevans** [comment] 2021-01-28 18:30
Please provide the example as minimal inline source code.  No rspec or migration needed, just the minimal self contained example that creates the table, creates the model, and runs the code showing the error.

I can tell you up front that `raise_on_save_failure`/`:raise_on_failure` only handles certain exception types (hook failures and validation failures) and not all exception types (such as database errors), by design.  So if you are getting an exception raised that is not a hook failure or a validation failure, then that is probably expected behavior.

**Comment by deemytch** [comment] 2021-01-28 19:34
Error, raised here in my example is exactly the database error.
So, if that is expected, could you mention that in docs?

**Comment by jeremyevans** [comment] 2021-01-28 19:54
Current documentation for `raise_on_save_failure`:

```
      # Whether to raise an error instead of returning nil on a failure
      # to save/create/save_changes/update/destroy due to a validation failure or
      # a before_* hook returning false (default: true).
```

Current documentation for `save` includes:

```
      # If +save+ fails and either raise_on_save_failure or the
      # :raise_on_failure option is true, it raises ValidationFailed
      # or HookFailed. Otherwise it returns nil.

      # :raise_on_failure :: set to true or false to override the current
      #                      +raise_on_save_failure+ setting
```

Considering that, do you think documentation changes are needed?

**Comment by jeremyevans** [comment] 2021-01-30 22:04
I'm going to close this now.  If you think documentation changes are needed, please submit a pull request for them.

**Closed by jeremyevans** 2021-01-30 22:04 UTC
