### ISSUE TITLE
ID auto increment is not working for Sequel::Model + PG

### ISSUE THREAD

**Issue by sanjay-btc** [jeremyevans/sequel#1618] opened 2019-05-06 12:08 UTC
I have a table already create by Rails migration. I have created a new Sinatra app and using sequel as ORM. Both apps(Rails + Sinatra) are sharing same database. I am using a class inherited from `Sequel::Model`. So essentially its model file.

But If I create a new record, it passes `null` value for the `id` column and I am getting `Sequel::NotNullConstraintViolation` error which is obvious.

I am not sure why it does not auto-increment the value of the `id`

Please note that, all tables are created by Rails migration and I am using Postgres DB.

Here is the model declaration and the syntax I am using to create the record in the DB
```
class Conversation < Sequel::Model
  set_primary_key :id
end

Conversation.create(customer_id: 1, updated_at: Time.now)
```

Backtrace of Exception

```
[2019-05-06T17:14:24.313447 #10649]  INFO -- : (0.000480s) BEGIN
E, [2019-05-06T17:14:24.320928 #10649] ERROR -- : PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, null, null, 2019-05-06 17:14:24.31257, 2019-05-06 17:14:24.311845, t).: INSERT INTO "conversations" ("updated_at", "created_at") VALUES ('2019-05-06 17:14:24.311845+0530', '2019-05-06 17:14:24.312570+0530') RETURNING *
I, [2019-05-06T17:14:24.322044 #10649]  INFO -- : (0.000492s) ROLLBACK
Sequel::NotNullConstraintViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, null, null, 2019-05-06 17:14:24.31257, 2019-05-06 17:14:24.311845, t).

```

Thank You!

**Comment by tycooon** [comment] 2019-05-06 12:12
I think you should check your migration code and your actual table structure using psql, for example.

**Comment by jeremyevans** [comment] 2019-05-06 13:46
As @tycooon indicated, this is a problem with your database, where there is no default autoincremented value for the primary key column.  Closing as this is not a bug in Sequel.

**Closed by jeremyevans** 2019-05-06 13:46 UTC
